export { default as Cards } from "./Cards/Cards";
export { default as Header } from "./Header/Header";
export { default as Feedback } from "./Feedback/Feedback";
export { default as Footer } from "./footer/Footer";
export { default as ScrollButton } from "./ScrollButton/ScrollButton";
export { default as Puzzle } from "./Puzzle/Puzzle";
export { default as MapContainer } from "./MapContainer/MapContainer";
export { default as SwiperParallax } from "./SwiperParallax/SwiperParallax";
export { default as SwiperLine } from "./SwiperLine/Swiper";
